# Generated by Django 3.1 on 2022-10-11 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='colar',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
